```{r}
install.packages("rio")
install.packages("stringr") 
install.packages("magrittr") 
install.packages("Hmisc")
install.packages("dplyr")  
install.packages("tidyr") 
install.packages("readr")

```

```{r}
library(rio)
library(stringr)
library(readr)
library(magrittr) 
library(Hmisc) #Para recodificar
library(dplyr) #Para recodificar 
library(tidyr)


```

```{r}
data1="https://github.com/AlmaGonzales/NIVELDEPOBREZA/raw/master/00.-Nacional-Matriz-Indicadores-Ceplan-Per%C3%BA-2007-2019_19May2020.xlsx"
pobreza=import(data1)
```

```{r}
pobreza=pobreza[-c(1,2,3,4,5,13,27,40,44,53,62,73,77,18,79,100,102,114,125,135,139,144,145,153,162,174,188,196,200,206,210,224),]
pobreza[,c(4:23)]=NULL
pobreza[,c(5,8,9,11,12,14,16:20)]=NULL
pobreza[,c(1,2,4)]=NULL

```

```{r}
names(pobreza)=gsub('\\s',"",names(pobreza))
names(pobreza) = c("Provincia", "%DesnutricioncronicaNiños2018","%AnemiaNiños2018","IDH2019","%Pobrezatotal2018","%Pobrezaextrema2018")

```

```{r}
str(pobreza)
```
```{r}
pobreza[!complete.cases(pobreza),] 
pobreza=na.omit(pobreza)
```

